name: MarlinAutoEnder3

on:
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'
  # trigger every night at 03:30
  schedule:
    - cron:  '11 0 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
     - uses: zisismaras/marlin_auto_build@v1
